project:
  type: website

website:
  title: "EpiForecasts"
  navbar:
    left:
      - text: "People"
        href: people.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Current projects"
        menu:
          - text: "Global Rt Tracking and Forecasting"
            href: https://epiforecasts.io/covid
          - text: "European Covid-19 Forecast Hub"
            href: https://covid19forecasthub.eu/
          - text: "Expert/Crowd Forecasting"
            href: https://www.crowdforecastr.org/
      - text: "Software"
        href: software.qmd
      - text: "Publications"
        href: pubs.qmd
    right:
      - icon: github
        href: https://github.com/epiforecast/epiforecasts.github.io

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
